---
name: Various Checks
# yamllint disable-line rule:truthy
permissions:
  contents: read
on: [push, pull_request]

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/devel/openqa/containers/tumbleweed:client
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - name: Validate yaml
        run: |-
          curl https://openqa.opensuse.org/schema/JobScenarios-01.yaml -O
          openqa-validate-yaml --schema-file JobScenarios-01.yaml scenario-definitions.yaml
